package com.presentation;

import com.presentation.entities.Company;
import com.presentation.entities.Presentation;
import com.presentation.entities.User;
import com.presentation.repositories.CompanyRepository;
import com.presentation.repositories.PresentationRepository;
import com.presentation.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.Date;

public class DatabaseFixture {

    //Usikker, men tror disse Repository variablene er sessions for å koble til DB
    @Autowired// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CompanyRepository companyRepository;
    @Autowired
    private PresentationRepository presentationRepository;
    @Autowired
    private UserRepository userRepository;

    public void populateDatabase(){

        //Companies
        Company bekk = new Company();
        bekk.setCompanyName("BEKK");
        bekk.setLogo("");
        bekk.setWebsite("bekk.no");
        bekk.setContactPerson("Kari nordmann");

        Company tv2 = new Company();
        tv2.setCompanyName("TV2");
        tv2.setLogo("");
        tv2.setWebsite("tv2.no");
        tv2.setContactPerson("Ola nordmann");
        System.out.print(tv2.getContactPerson());

        //TODO: nullpointer exceptions here
        //companyRepository.save(bekk);
        //companyRepository.save(tv2);

        //Presentations
        Presentation presentationTV2 = new Presentation();
        presentationTV2.setDateOfPresentation(new Date(System.currentTimeMillis()));//Just used current time.
        presentationTV2.setCompanyPresenting(tv2);
        presentationTV2.setMaxAttendance(20);
        presentationTV2.setContactPerson(tv2.getContactPerson());
        presentationTV2.setMeetupAdress("Media city");
        presentationTV2.setDescription("Bedriftpresentasjon med tv2");

        Presentation presentationBekk = new Presentation();
        presentationTV2.setDateOfPresentation(new Date(System.currentTimeMillis()));//Just used current time.
        presentationTV2.setCompanyPresenting(bekk);
        presentationTV2.setMaxAttendance(20);
        presentationTV2.setContactPerson(bekk.getContactPerson());
        presentationTV2.setMeetupAdress("Høyteknologi senteret");
        presentationTV2.setDescription("Bedriftpresentasjon med bekk");

        //presentationRepository.save(presentationTV2);
        //presentationRepository.save(presentationBekk);

        //Users
        User henrik = new User();
        henrik.setFirstName("Henrik");
        henrik.setLastName("Hexeberg");
        henrik.setEmail("henrik@email.com");
        henrik.setStudy("Security");
        henrik.setYear("Fourth year");

        User eirin = new User();
        eirin.setFirstName("Eirin");
        eirin.setLastName("Sognnes");
        eirin.setEmail("Eirin@email.com");
        eirin.setStudy("PU");
        eirin.setYear("Fourth year");

        User malik = new User();
        malik.setFirstName("Malik");
        malik.setLastName("Aasen");
        malik.setEmail("Malik@email.com");
        malik.setStudy("PU");
        malik.setYear("Fourth year");

        User eivind = new User();
        eivind.setFirstName("Eivind");
        eivind.setLastName("Dagsland Halderake");
        eivind.setEmail("Eivind@email.com");
        eivind.setStudy("PU");
        eivind.setYear("Fourth year");

        //userRepository.save(henrik);
        //userRepository.save(eirin);
        //userRepository.save(malik);
        //userRepository.save(eivind);

    }

}
